### ISSUE TITLE
[selectors] Add `:open` or `:top-layer` pseudo class

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#924] opened 2022-10-11 07:35 UTC
A resolution was made for [csswg-drafts/#7319](https://github.com/w3c/csswg-drafts/issues/7319).

**\[selectors\] Add \`:open\` or \`:top\-layer\` pseudo class**

* RESOLVED: start work on an :open as a pseudo class, which matches things that are in an "open" state.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1274222201)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment] 2022-10-11 23:51
Dupe of #878, which I should close as it's just about spec-work.

**Closed as completed by dholbert** 2022-10-11 23:51 UTC
