### ISSUE TITLE
[css-grid][css-flexbox][quirks] Avoid percentage height quirk in new layout models

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#443] opened 2020-12-09 18:58 UTC
A resolution was made for [csswg-drafts/#5545](https://github.com/w3c/csswg-drafts/issues/5545).

**\[css\-grid\]\[css\-flexbox\]\[quirks\] Avoid percentage height quirk in new layout models**

* RESOLVED: dholbert to make a change to quirks spec to clarify behavior for flex and grid items and containers

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5545#issuecomment-741979921)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment] 2020-12-09 19:04
Huh, this issue is effectively a duplicate of https://github.com/mozilla/wg-decisions/issues/442

This version here seems to have been spawned by the fact that I quoted a `RESOLVED` line in a github-reply on https://github.com/w3c/csswg-drafts/issues/5545#issuecomment-741979921 .  My reply with that RESOLVED quote seems to have made mozilla-apprentice think that there might be a new resolution needing new action.

Note-to-self: don't type or quote "RESOLVED" in csswg spec issues, or else apprentice will jump on it. :)

**Closed as completed by dholbert** 2020-12-09 19:04 UTC
Labels: [spec] css-grid-1, [spec] css-flexbox-1

**Comment by Loirooriol** [comment] 2020-12-09 19:17
@dholbert I use `RES0LVED` with number zero instead of letter O to avoid this problem :)

**Comment by jfkthame** [comment] 2020-12-09 19:30
To confuse people further, you could go with RESΟLVED (using Greek Omicron) or RESОLVED (using Cyrillic О) ... I bet moz-apprentice doesn't look for those. Let people waste hours wondering why their searches don't work! ;)

**Comment by heycam** [comment] 2020-12-23 05:03
Sorry the apprentice is still learning. :-)  I should teach it to avoid quoted text.  Filed https://github.com/heycam/wg-tracker/issues/3.
