### ISSUE TITLE
[scroll-animations-1] blocking effects of timeline-scope

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1225] opened 2023-08-21 08:26 UTC
A resolution was made for [csswg-drafts/#8915](https://github.com/w3c/csswg-drafts/issues/8915).

**\[scroll\-animations\-1\] blocking effects of timeline\-scope**

* RESOLVED: contain:style prevents timeline names from leaking out past it

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8915#issuecomment-1685881216)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment] 2023-08-22 19:30
Dupe of #1194 (spawned by a github comment-quote of "RESOLVED:...")

**Closed as completed by dholbert** 2023-08-22 19:30 UTC
Labels: [spec] css-contain-1, [spec] css-contain-2, [spec] scroll-animations-1, [spec] css-animations-2
