### ISSUE TITLE
[css-text] Tabs and the end of the line with pre-wrap and break-word

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#493] opened 2021-03-16 08:05 UTC
A resolution was made for [csswg-drafts/#6062](https://github.com/w3c/csswg-drafts/issues/6062).

**\[css\-text\] Tabs and the end of the line with pre\-wrap and break\-word**

* RESOLVED: For white\-space:pre\-wrap tabs hang like spaces do

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6062#issuecomment-800045501)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment] 2021-03-16 15:59
Dupe of #77 .  (This one got spawned by a github comment that was quoting a resolution.)

**Closed as completed by dholbert** 2021-03-16 15:59 UTC
Labels: [spec] css-text-3
