### ISSUE TITLE
[css-values-4] min/max(%, %) should explicitly evaluate against the % value, not the resolved value

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#474] opened 2021-01-28 16:18 UTC
A resolution was made for [csswg-drafts/#4227](https://github.com/w3c/csswg-drafts/issues/4227).

**\[css\-values\-4\] min/max\(%, %\) should explicitly evaluate against the % value, not the resolved value**

* RESOLVED: Close no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4227#issuecomment-769198360)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment] 2021-01-28 19:10
Dupe of #473

**Closed as completed by dholbert** 2021-01-28 19:10 UTC
Labels: [spec] css-values-4
